sudo: required
services:
  - docker
before_script:
  - docker build -t go-dev-tools:tmp -f ./tools/Dockerfile-tools .
script:
  - docker run --rm -v "$(pwd):/app" go-dev-tools:tmp -c 'task lint'
  - docker run --rm -v "$(pwd):/app" go-dev-tools:tmp -c 'task test'
  - docker-compose -f docker-compose.test.yml up --exit-code-from tests --abort-on-container-exit
after_script:
  - docker-compose -f docker-compose.test.yml down